name: automexa_apis
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/automexa/automexa
repository: https://github.com/automexa/automexa
issue_tracker: https://github.com/automexa/automexa/issues 
documentation: https://youtube.com/@automexa
funding:
  - https://github.com/sponsors/automexa


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:
 
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
